H2M2chat-main/src/H2M2chat/Controllers/ChatRoomController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using H2M2chat.Data;
using H2M2chat.Models;
using Microsoft.AspNetCore.Authorization;

namespace H2M2chat.Controllers
{
    public class ChatRoomController : Controller
    {
        private readonly AppDbContext _context;

        public ChatRoomController(AppDbContext context)
        {
            _context = context;
        }

        // GET: ChatRoom
        [Authorize]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Room.ToListAsync());
        }
        [Authorize]
        // GET: ChatRoom/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .FirstOrDefaultAsync(m => m.RoomId == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }
        [Authorize]
        // GET: ChatRoom/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ChatRoom/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("About,IsGC,IsVisable")] Room room)
        {
            if (ModelState.IsValid)
            {
                room.RoomId = Guid.NewGuid();
                room.RoomIcon = Guid.NewGuid();
                _context.Add(room);
                await _context.SaveChangesAsync();
                return Redirect($"~/ChatRoom/Details/{room.RoomId}");
            }
            return View(room);
        }

        // GET: ChatRoom/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room.FindAsync(id);
            if (room == null)
            {
                return NotFound();
            }
            return View(room);
        }

        // POST: ChatRoom/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(Guid id, [Bind("RoomId,About,IsGC,IsVisable")] Room room)
        {
            if (id != room.RoomId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(room);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoomExists(room.RoomId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect($"~/ChatRoom/Details/{room.RoomId}");
            }
            return View(room);
        }

        // GET: ChatRoom/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var room = await _context.Room
                .FirstOrDefaultAsync(m => m.RoomId == id);
            if (room == null)
            {
                return NotFound();
            }

            return View(room);
        }

        // POST: ChatRoom/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var room = await _context.Room.FindAsync(id);
            _context.Room.Remove(room);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoomExists(Guid id)
        {
            return _context.Room.Any(e => e.RoomId == id);
        }
    }
}

H2M2chat-main/src/H2M2chat/Controllers/TopicsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using H2M2chat.Data;
using H2M2chat.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;

namespace H2M2chat.Controllers
{
    public class TopicsController : Controller
    {
        private readonly AppDbContext _context;

        public TopicsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Topics
        public async Task<IActionResult> Index(string search,string tag)
        {
            var Topics = from m in _context.Topic
                         select m;
            if (!String.IsNullOrEmpty(search))
            {
                Topics = Topics.Where(s => s.Title!.Contains(search));
            }
            if (!String.IsNullOrEmpty(tag))
            {
                Topics = Topics.Where(s => s.Tags!.Contains(tag));
            }

            return View(await Topics.ToListAsync());
        }

        
        // GET: Topics/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.TopicId == id);
            
            if (topic == null)
            {
                return NotFound();
            }
            var comments = from m in _context.Comment
                           select m;
            comments = comments.Where(s => s.TopicId == id );

            topic.Comments = comments.Where(s => s.level == 0).ToList();
            foreach (var comment in topic.Comments)
            {
                comment.SubComments = comments.Where(s => s.level == 1 && s.ParentId==comment.CommentId).ToList();
                foreach(var subComment in comment.SubComments)
                {
                    subComment.SubComments = comments.Where(s => s.level == 2 && s.ParentId == subComment.CommentId).ToList();
                }
            }



            return View(topic);
        }

       /* // GET: Topics/Create
        public IActionResult Create()
        {
            return View();
        }*/

        // POST: Topics/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,Tags")] Topic topic)
        {
            if (ModelState.IsValid)
            {
                topic.TopicId = Guid.NewGuid();
                topic.Title = System.Net.WebUtility.HtmlEncode(topic.Title);
                topic.Description = System.Net.WebUtility.HtmlEncode(topic.Description);
                topic.Tags = System.Net.WebUtility.UrlEncode(topic.Tags);
                topic.Creator = User.Identity.Name;
                _context.Add(topic);
                await _context.SaveChangesAsync();
                
                return Redirect($"~/Topics/Details/{topic.TopicId}");
            }
            
            return Redirect("~/");
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Comment([Bind("TopicId,ParentId,Message")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.CommentId = Guid.NewGuid();
                comment.Creator = User.Identity.Name;
                comment.Message = System.Net.WebUtility.UrlEncode(comment.Message);
                if (comment.ParentId == Guid.Empty)
                {
                    comment.level = 0;
                    var topic = await _context.Topic
                    .FirstOrDefaultAsync(m => m.TopicId == comment.TopicId);
                    /*topic.Comments.Add(comment);
                    
                    _context.Update(topic);*/
                    
                }
                else
                {
                    var subcomment = await _context.Comment
                   .FirstOrDefaultAsync(m => m.CommentId == comment.ParentId);
                    comment.level = subcomment.level + 1;
                    if (comment.level == 3)
                    {
                        return Redirect($"~/Topics/Details/{comment.TopicId}");
                    }
                    /*subcomment.SubComments.Add(comment);
                    _context.Update(subcomment);*/

                }
                _context.Comment.Add(comment);
                await _context.SaveChangesAsync();
                return Redirect($"~/Topics/Details/{comment.TopicId}");

            }

            /*Console.WriteLine(ModelState.Values.SelectMany(v => v.Errors));*/
            return Redirect("~/");
        }


        /*// GET: Topics/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic.FindAsync(id);
            if (topic == null)
            {
                return NotFound();
            }
            return View(topic);
        } */

        // POST: Topics/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid? TopicId,String Title,String Description,String Tags)
        {

            
            

            if (TopicId != null)
            {
                var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.TopicId == TopicId);
                topic.Description = System.Net.WebUtility.HtmlEncode(Description);
                topic.Tags = System.Net.WebUtility.HtmlEncode(Tags);
                topic.Title = System.Net.WebUtility.HtmlEncode(Title);
                if (topic.Creator == User.Identity.Name)
                {
                    
                    try
                    {
                        _context.Update(topic);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!TopicExists(topic.TopicId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return Redirect($"~/Topics/Details/{topic.TopicId}");
                }
                else
                {
                    return Forbid("Not in my website :3");
                }
                
            }
            return NotFound(); ;
        }
        /*
        // GET: Topics/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.TopicId == id);
            if (topic == null)
            {
                return NotFound();
            }

            return View(topic);
        }*/

        // POST: Topics/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid? TopicId)
        {
            if (TopicId == null)
            {
                
                return NotFound();
            }

            var topic = await _context.Topic
                .FirstOrDefaultAsync(m => m.TopicId == TopicId);

            if (topic == null)
            {
                return NotFound();
            }
            
            if (topic.Creator == User.Identity.Name)
            {
                var comments = from m in _context.Comment
                               select m;
                comments = comments.Where(s => s.TopicId == TopicId);
                _context.Comment.RemoveRange(comments);
                _context.Topic.Remove(topic);
                await _context.SaveChangesAsync();
            }
            else
            {
                return Forbid("Not in my website :3");
            }

            return RedirectToAction(nameof(Index));
        }

        private bool TopicExists(Guid id)
        {
            return _context.Topic.Any(e => e.TopicId == id);
        }
    }
}

H2M2chat-main/src/H2M2chat/Views/Shared/_Chats.cshtml
@*@model IEnumerable<H2M2chat.Models.Room>*@

<div id="menu">
  <input type="checkbox" id="menu-toggle"/>
  <ul class="Chatul">
    <li class="Chat1ist">
      <a href="#">&#x2708;</a>
    </li><li class="Chat1ist">
      <a href="#">&#x266b;</a>
    </li><li class="Chat1ist">
      <a href="#">&#x2709;</a>
    </li><li><i class="fas fa-user-plus"></i></li>
  </ul>
</div>

H2M2chat-main/src/H2M2chat/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - H2M2chat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/H2M2chat.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" asp-append-version="true"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src = "~/Images/logo.png" alt="logo" height="50px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Topics" asp-action="Index">Topic Discussion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ChatRoom" asp-action="Index">ChatRoom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
           @* if (SignInManager.IsSignedIn(User))
            {
                @{await Html.RenderPartialAsync("_Chats");}
            }*@
              
            
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - H2M2chat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>